### ISSUE TITLE
Lazy load stripe.js

### ISSUE THREAD

**Issue by machty** [code-corps/ember-stripe-elements#11]
Correct me if I'm wrong but it seems that if a user opens the app while they don't have internet, then if they try and open the credit card form later, when they do have internet, the app will break due to the stripe.js not being loaded.

The way I handled this is pretty adhoc, but would you be interested in a PR to bring lazy-loading (plus retrying upon transient failure) of the stripe.js lib?

**Comment by JoshSmith** [comment]
@machty yes, I think this has been a frustration for others.

Are you expecting that the consuming application would be able to gracefully recover from this situation via some API relating to its status? (i.e. perhaps I don't want to try and fail to render a credit card form when the JS is not loaded).

Regardless of the approach, I would love to see something here. Feel free to spike and/or pseudocode as much as you'd like for feedback.

Thanks for thinking about bringing this in!

**Comment by JoshSmith** [comment]
Hey @machty, I've been gone for awhile so hadn't had time to check back in with you until recently. Wanted to see if this was still of interest for you?

**Comment by JoshSmith** [comment]
We can pull in some of the things learned in [this PR](https://github.com/code-corps/ember-stripe-service/pull/59) on `ember-stripe-service` to incorporate lazy loading here.

**Comment by JoshSmith** [comment]
Apologies this has taken nearly so long to implement. I'm about to merge a PR and should shortly release an `rc` that includes lazy loading and mocking by default.

**Comment by JoshSmith** [comment]
Released on `0.2.0`.
