### ISSUE TITLE
Example of using individual element types in docs

### ISSUE THREAD

**Issue by ChrisLincoln** [code-corps/ember-stripe-elements#12]
I've got an integration working using the {{stripe-card}} component using a block.  I would like to take more control over style and positioning, which is what I presume {{stripe-card-number}} et. al. are for.  I can't seem to wrap my head around how to using these and gain access to their stripeElement for the code in my submit button handler. 

Do you have an example of these?

**Comment by ChrisLincoln** [comment]
Great. Thank you!

**Comment by JoshSmith** [comment]
@ChrisLincoln @andrewfan would you be interested in improving the docs to add some examples here?

**Comment by ChrisLincoln** [comment]
@JoshSmith, I ended up using the full {stripe-card} and as such do not have an example to offer. It is likely that we will break that down into the constituent parts. When we do, I will gladly back-fill the docs with an example from the effort.

**Comment by JoshSmith** [comment]
We do have in the dummy app an example of the constituent parts. Have you had a chance to check those out?
