### ISSUE TITLE
createSource, retrieveSource, etc not available 

### ISSUE THREAD

**Issue by dja** [code-corps/ember-stripe-elements#15]
Following the documentation here: https://github.com/code-corps/ember-stripe-elements#features, and finding that `createSource`, `retrieveSource`, and the other functions for `Stripe` are not available. I'm only seeing `elements` and `createToken` available.

**Comment by JoshSmith** [comment]
Hm that's odd. The relevant lines are here: https://github.com/code-corps/ember-stripe-elements/blob/master/addon/services/stripev3.js#L20

How have you been trying to call this?

**Comment by JoshSmith** [comment]
@digia you had originally added these lines. Any thoughts here?

**Comment by dja** [comment]
@JoshSmith perhaps it's because the npm version is behind these updates? https://www.npmjs.com/package/ember-stripe-elements

**Comment by JoshSmith** [comment]
@dja almost certainly it. For now can you pull from GitHub until I can cut a release?

**Comment by digia** [comment]
Ya, as @JoshSmith said it hasn't been released yet =P

**Comment by JoshSmith** [comment]
I'm going to work on bringing this up to speed for a new release today. It's been bugging me and I just haven't had time for it, but I'm just going to make time now.

**Comment by JoshSmith** [comment]
Made available now in `master` and will be released shortly. Closing for now.
