### ISSUE TITLE
Stripe Card Error thrown when invalid card entered "The default action was triggered "Assertion Failed: The default action was triggered on the component... but the action name ([object Object]) was not a string."

### ISSUE THREAD

**Issue by OakBehringer** [code-corps/ember-stripe-elements#22]
In template:

```
{{stripe-card}}
```

Enter an intentionally wrong card number (such as "8768 7658 7686 8766"), and the console shows an exception: 

> Assertion Failed: The default action was triggered on the component [component id], but the action name ([object Object]) was not a string.

![image](https://user-images.githubusercontent.com/2909414/34020465-2f116cea-e0e9-11e7-8ea9-4e874e8afab8.png)

![image](https://user-images.githubusercontent.com/2909414/34020469-39ba32b2-e0e9-11e7-8414-aae0faed252f.png)

**Comment by joshsmith** [comment]
Thanks for the bug report! I'll try to look into why that's happening here soon.

If you'd like to help debug the reasoning behind it, please do feel free to fork the repo and try it out in the dummy app.

**Comment by snewcomer** [comment]
@joshsmith @OakBehringer I think the reason behind this is internally, ember says `get me anything named "error"` on this component and it finds the .  Since it is already set to an object, it tries to validate that object and fails.  

PR #23

**Comment by joshsmith** [comment]
Good hunting! I have some questions on the PR, but it looks like we can likely get this merged shortly and I'll cut a point release for the fix for you @OakBehringer.

**Comment by joshsmith** [comment]
Out of curiosity, did you find this in any exception tracking?

**Comment by joshsmith** [comment]
@OakBehringer this should be published now as 0.3.0 on npm. Thanks so much again for reporting the issue and for your patience while it got fixed.

🙌  to @snewcomer for working fixing this.
