### ISSUE TITLE
Assertion Failed: Attempting to inject an unknown injection: 'service:stripev3'

### ISSUE THREAD

**Issue by ngkarkeong** [code-corps/ember-stripe-elements#28]
i am new to fronted development. and ember.
i try to setup the environment. and i got this error message.  
Any suggestion what went wrong? thanks

**Comment by amiel** [comment]
Hi @ngkarkeong, I have a few clarifying questions:

Where are you seeing this message?
In your tests or in the browser for development?
Have you restarted your server after installing the addon?

**Comment by ngkarkeong** [comment]
it was showed on broswer.
i got a fix by restart the server. thanks for taking time to suggest.
