### ISSUE TITLE
Multiple Publishable Keys

### ISSUE THREAD

**Issue by Paskalouis** [code-corps/ember-stripe-elements#39]
Hi,

I am currently having the condition where the publishable key can be different because there are conditions that may change the Stripe Account, which means setting different publishable key.
I see that we can only set one publishable key on environment.js , and if I don't set anything there, my application went error.
![image](https://user-images.githubusercontent.com/5112688/43245912-378deb2c-90da-11e8-9e16-c29fe4b7887c.png)

I am thinking that will there will be support for setting up publishable key 'later', not in environment.js, but when I want / need to.

Thank you

**Comment by ghedamat** [comment]
@Paskalouis just ran into this myself today

didn't have time to think about a PR yet but my current solution is to implement my own stripe service and override the `publishableKey` property 

not super elegand but does the trick until this is addressed

**Comment by danwenzel** [comment]
@Paskalouis - We had a similar need, and got around this by manually setting the stripe service's `config.publishableKey` right before loading.  As long as you lazy load and don't need to change the key afterwards, it should work:

```js
this.stripev3.set('config.publishableKey', key);
return this.stripev3.load();
```

**Comment by lindyhopchris** [comment]
#59 has added the ability to provide the publishable key when calling `stripev3.load()`.

Do people have a requirement though to toggle the publishable key... i.e. to change it after it has already been set? If so, do you know if this works with Stripe?

**Comment by Paskalouis** [comment]
@danwenzel @lindyhopchris 
Hi, nice solution you got there.

Yes, in some cases, people may need to toggle the publishable key.
I have the condition from this issue, where in my business problem needs to have 2 or more stripe accounts to handle, based on specific set of conditions, so I need to change it based on those conditions.
However it is already solved, so I will close this issue.

Thank you !

**Comment by st-h** [comment]
just noticed I forgot to add another way to work around this here: I am building the ember app with a unique placeholder as the stripe key. When deploying the app, this placeholder gets replaced (via a sed command) with the actual stripe key. That way we can deploy the same artifact using different configs e.g. for test and prod
