### ISSUE TITLE
support for createPaymentMethod

### ISSUE THREAD

**Issue by adambedford** [code-corps/ember-stripe-elements#45]
Is this library still maintained and has anyone had success adding newer strip v3 methods such as createPaymentMethod?

**Comment by pablobm** [comment]
Looks like you fixed this one yourself at https://github.com/code-corps/ember-stripe-elements/pull/46? :-)

Thank you for that! Now it's a matter of the maintainer publishing a new version.

**Comment by lindyhopchris** [comment]
This has been fixed on `develop` via #50 - will close when we have a tagged version from `develop`.

**Comment by mkimont** [comment]
Any updates about this task ?

**Comment by lindyhopchris** [comment]
@kimek believe if you use `develop` it should work... we're not getting tagged versions at the mo, worht following #66

**Comment by st-h** [comment]
please see https://github.com/adopted-ember-addons/ember-stripe-elements or https://www.npmjs.com/package/@adopted-ember-addons/ember-stripe-elements for current versions
