### ISSUE TITLE
Remove jQuery usage

### ISSUE THREAD

**Issue by josemarluedke** [code-corps/ember-stripe-elements#54]
This addon should be refactored away from jQuery.

jQuery is now optional in Ember and will be disabled by default in the Ember v3.13.

Our apps also don't have jQuery, which block us to use this addon.

**Comment by st-h** [comment]
A similar PR has been merged into master a while ago: https://github.com/code-corps/ember-stripe-elements/pull/42
I think the developer branch should be removed #51 . However, I don't have any information about the current state of this repo 😟

**Comment by lindyhopchris** [comment]
@st-h we've both now got access rights to this repo which is a good step. we just need the ability to tag on npm... any chance you were given access to do that?

**Comment by st-h** [comment]
@lindyhopchris nope. I have been invited by @joshsmith - who then soon disappeared again. I pretty much don't know anything about what is going on with this repo.
As of #38 it looks like the npm token currently is one of the blocking issues

**Comment by lindyhopchris** [comment]
I believe @joshsmith intent was to enable us to manage the repo, so I'm taking the view that we can start merging stuff and sorting things out. All of this is quite pressing with the amount of changes people (like me!) are making to their implementations for the upcoming SCA rules.

As we can now do things on the repo, the only thing left is for npm access to tag new releases... hopefully josh can grant that soon!

**Comment by lindyhopchris** [comment]
ah i see what you mean - they've potentially got automated npm releases set up but the configuration isn't right at the mo?
