### ISSUE TITLE
SCA compliance

### ISSUE THREAD

**Issue by idgm81** [code-corps/ember-stripe-elements#57]
Hi guys

Just a question. Last version is ready for SCA compliance? https://stripe.com/docs/strong-customer-authentication

Thanks!

**Comment by danwenzel** [comment]
@idgm81 - There has been a lot of recent activity on this repo related to SCA, including this PR: https://github.com/code-corps/ember-stripe-elements/pull/50, which added all of the current methods available on the strive v3 object.

Although I haven't tried it yet myself, I believe these methods should get you what you need on the frontend for SCA compliance.  This PR has been merged, and we're just waiting for a new release

**Comment by lindyhopchris** [comment]
Yeah you'll need to use the `develop` branch, but should be able to do the SCA compliant stuff with that. Hoping to get a new tagged version soon once we've got in contact with the repo owner.

**Comment by idgm81** [comment]
Thanks for the info! I will watch for news
