### ISSUE TITLE
Publish new version of the package

### ISSUE THREAD

**Issue by pablobm** [code-corps/ember-stripe-elements#63]
There have been some PRs merged since the last release, which is over a year old. Currently my dependency list refers to this package as a URL to the appropriate Git SHA, as we depend on one of these new features.

* What is stopping this project from publishing an updated version of the package?
* What can we do to help remove blockers?

**Comment by st-h** [comment]
@pablobm afaik the main reason is that no one who is active within this repo has the actual permission to release on npm. I think, most likely @joshsmith has some information about that - but I pretty much can only speculate on that.

**Comment by lindyhopchris** [comment]
Yeah I think the only thing blocking this is getting hold of @joshsmith  I've been given permission to do things on this repo but don't have any npm permissions. I don't necessarily need npm permissions as it might be taken care of if #38 is fixed.

I'm in the same position as you, and I'm guessing there's lots of us in the same position what with the upcoming SCA changes. 

cc @begedin who might be able to help?

**Comment by bartocc** [comment]
Just a comment to +1 that I landed on this issue because of SCA changes as well.

**Comment by lindyhopchris** [comment]
@joshsmith ping again. we really really need your help here to get tagged versions of this out.

**Comment by pablobm** [comment]
@lindyhopchris - See https://twitter.com/joshsmith/status/1166627831725666304

**Comment by lindyhopchris** [comment]
@pablobm thanks for the tip-off, don't use Twitter much! Will send him a message now.

**Comment by pjcarly** [comment]
Any updates on this?

**Comment by lindyhopchris** [comment]
I've messaged @joshsmith multiple times via Twitter and not had a response.

**Comment by st-h** [comment]
please see https://github.com/adopted-ember-addons/ember-stripe-elements or https://www.npmjs.com/package/@adopted-ember-addons/ember-stripe-elements for current versions
