### ISSUE TITLE
RFC: the future of this repo

### ISSUE THREAD

**Issue by st-h** [code-corps/ember-stripe-elements#66]
It's been about 8 month now since I decided to [release a fork of this addon](https://www.npmjs.com/package/@st-h/ember-stripe-elements) as I have been in dire need of an addon that allows to use stripe with ember. Since then much has happened, most importantly this repo has received quite some attention and a reasonable amount of contributions - which is pretty awesome. I and @lindyhopchris have been given permission to edit this repo - However, we still have not been able to sort out a few core issues like being able to publish new versions of this addon to npm. Secondly, we haven't been able to get much information about code-corps plans for this addon and the future.

I was thinking about releasing another update within the scope of my previous fork. But I personally do not feel very comfortable fully adopting another addon, as there usually are drawbacks like making the future of an addon depending on the very specific need and available time of a person or company. Plus, I right now do not have much time available to even maintain my other addons.

Instead I would like to propose moving ember-stripe-elements to [adopted-ember-addons](https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md). I haven't taken any steps towards this, as I would like to get input on that idea here first. 
However, as a lot of commercial apps will need a way to handle billing, I think this will be an appropriate place for this addon. Also, I hope this will no longer cause future releases being dependent on the availability of one or two devs (who probably are busy getting other stuff done)

Disclaimer: I do not have any personal experience with adopted-ember-addons. If you have been going through that transfer in the past, please add your input.

**Comment by lindyhopchris** [comment]
@st-h great write up and I think this makes a lot of sense as a way forward.

**Comment by lougreenwood** [comment]
Completely agree - the lack of a release after SCA was made mandatory is a disaster for this add-on.

@joshsmith - where are you?

**Comment by knownasilya** [comment]
Can anyone at code corps make this happen?

Trying to get some eyes on it https://twitter.com/knownasilya/status/1182363353215315968

**Comment by averydev** [comment]
Hi all!  Any movement here? Or suggestions as path forward?

**Comment by lindyhopchris** [comment]
Still no response, I've also tweeted again https://twitter.com/chrisgammie/status/1189139228690731008?s=20

Very frustrating as there's definitely the demand to take this repo forward. We just need to get it moved out of code-corps then we'll get traction...

**Comment by st-h** [comment]
I feel somewhat reluctant here, as I really don't want to "take away" this repo from the org I have been invited to, without having at least someone state that it is ok. However, it is almost a year now since I [started to investigate](https://github.com/code-corps/ember-stripe-service/issues/69) what is going on with this repo.
There has been some more investigation about what is going on over at the discord adopted-ember-addons channel, but even other people that are committing to code corps repos seem to be unaware of this repo. For instance:

> @snewcomer 
> I don't remember my permissions on that repo.  Looks like commits are being made.  Is the issue publishing?  Or is the need for someone to review the v3 update? 

Given that this is going on for over a year now, I guess probably its best to just move on, as we will likely never get any statement if its ok to continue this addon at a different place. I think for the next steps, we should enquire again with adopted-ember-addons if they are ok with this situation and then we will need to follow the [guidelines here](https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md). I don't think there are any technical issues that would prevent us from doing so - there even seems to be a process to adopt the npm package:

> jrjohnson10/12/2019
> if you can't reach the original author NPM has a process to adopt the package https://www.npmjs.com/policies/disputes

But I think we could also release under a different scope, which will likely be way less invasive (as code corps still will be able to publish if they would like to continue this Addon one day)

**Comment by averydev** [comment]
@lindyhopchris @st-h Thanks for working on this!

**Comment by lindyhopchris** [comment]
@st-h hope you're all good!

Still no response, I've tried sending one more message. I think let's give it until the end of the year (as that's almost upon us), and then take it forward.

I'm going full-time on my own company then and our product uses this repo. I prefer the idea of moving it to Ember adopted addons if that's an option... if not I'd be willing to fork and publish under a different scope?

**Comment by jherdman** [comment]
Hey friends. So, what's the call here? Should @st-h's fork be "blessed"?

**Comment by snewcomer** [comment]
Let's do it.  the `adopted-ember-addons` is the proper place for this addon.  If we can bring the history over, then great.  Otherwise, if not, the need to improve supersedes a proper migration path at this point.

**Comment by jherdman** [comment]
I'm happy to volunteer to start the [adoption process](https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md), but before I do I thought I'd discuss a plan.

It's my understanding that @st-h's fork has some pretty valuable changes. Ought we to use that as the base, or just fork from master on this repo?

**Comment by st-h** [comment]
sorry about the late reply. Been quite busy with a lot of other code. First off: Please do not use my fork. All the changes I have made have been added to this repo here and this repo has more recent changes as well.

I personally think the best way to move forward would be to fork this Addon somewhere where it is under `adopted-ember-addons` control and release under a different npm scope.
As far as I have been talking to the `adopted-ember-addons` members, there should not be a problem with adoption.

@jherdman would be great if you could take care of this, I just can't make up enough time at the moment to do so. I'll be happy to help where I can though. Afaik there is a dev branch as well. @lindyhopchris do you know which branch would be best to pick as a starting point?

**Comment by lindyhopchris** [comment]
@jherdman thanks so much for your message and offer of taking forward the adoption process.

@st-h yeah agree with what you've said! best thing is just to get something in adopted addons.

> do you know which branch would be best to pick as a starting point?

yeah `develop` has the latest changes on it. If we're starting from scratch, then maybe it'd make sense to tag an immediate release (e.g. `0.1.0`), then sort out anything that needs sorting before tagging a `1.0.0` release.

**Comment by st-h** [comment]
So far, our app finally made some sales 🎉 and we're upgrading our stripe integration, so I'll try to take care of some things to move this Addon forward today.

We finally have a new repo: https://github.com/adopted-ember-addons/ember-stripe-elements

Regarding the somewhat controversial issue #51: I've merged the `dev` branch into the current `master` (merge conflicts included). For now I will remove the `dev` branch as I personally think it does more harm than good for small projects (well it already did, if you scroll through the issues). However, we can easily bring it back, if we should need it in case the repo gets a lot more attention and contributions. Hope this is ok for everyone.

**Comment by st-h** [comment]
I have opened a new branch https://github.com/adopted-ember-addons/ember-stripe-elements/tree/cli-upgrade which updates dependencies and fixes some newer linting errors. I would like to release this branch as an `1.0.0` release candidate. Please submit your PRs if you want something included.

The current `master` branch (with all the changes from the old `dev` branch) will be released as `0.5.0`.

We should have npm set up for `@adopted-ember-addons/ember-stripe-elements` tomorrow.

**Comment by lindyhopchris** [comment]
@st-h that all sounds great!

**Comment by st-h** [comment]
We have a release https://www.npmjs.com/package/@adopted-ember-addons/ember-stripe-elements
`1.0.0-rc.0` will follow today

I have also added a notice to this repo.

If you want to help maintain this add-on, please get in touch with the adopted-ember-addons team.

**Comment by st-h** [comment]
`1.0.0-rc.0` is out as well: https://www.npmjs.com/package/@adopted-ember-addons/ember-stripe-elements
Thanks a lot to Alon from the adopted-ember-addons team, who helped getting everything set up.

**Comment by st-h** [comment]
@lindyhopchris I was wondering if you would like to get permissions to maintain this addon over at adopted-ember-addons as well?

**Comment by lindyhopchris** [comment]
@st-h yes happy to do that. it's a critical addon for what I'm working on, so I'm happy to help maintain as part of a team.
